dataset :
  train : /home/ptn/Storage/Research/FFESNet/data/TrainDataset/Mix-Kvasir-ClinicDB
  valid : /home/ptn/Storage/Research/FFESNet/data/TestDataset
  test  : /home/ptn/Storage/Research/FFESNet/data/TestDataset

model:
  model_name      : 'FFESNet_B4'
  model_backbone  : 'B4'

hyparameters:
  init_trainsize  : 352
  batch_size      : 16
  repeats         : 1
  n_epochs        : 250
  learning_rate   : 1e-4
  drop_rate       : 0.2