dataset :
  train : /home/ptn/Storage/Research/FFESNet/data/Kvasir_Splited/trainSplited
  valid : /home/ptn/Storage/Research/FFESNet/data/Kvasir_Splited/validationSplited
  test  : /home/ptn/Storage/Research/FFESNet/data/Kvasir_Splited/testSplited

model:
  model_name      : 'LA_FFESNet_B4_Kvasir'
  model_backbone  : 'B4'

hyparameters:
  init_trainsize  : 352
  batch_size      : 16
  repeats         : 1
  n_epochs        : 250
  learning_rate   : 1e-4
  drop_rate       : 0.2