dataset :
  train : /home/ptn/Storage/FFESNet/data/Kvasir_Splited/trainSplited
  valid : /home/ptn/Storage/FFESNet/data/Kvasir_Splited/validationSplited
  test  : /home/ptn/Storage/FFESNet/data/Kvasir_Splited/testSplited

model:
  model_name      : 'LA_FFESNet_PAN_Kvasir'
  model_backbone  : 'B4'
  model_pyramid   : 'PANet'
  use_le          : True
  use_aa          : True

hyparameters:
  init_trainsize  : 352
  batch_size      : 16
  repeats         : 1
  n_epochs        : 100
  learning_rate   : 1e-4
  drop_rate       : 0.2