dataset :
  train : /home/ptn/Storage/Research/FFESNet/data/CVC-ClinicDB_Splited/trainSplited
  valid : /home/ptn/Storage/Research/FFESNet/data/CVC-ClinicDB_Splited/validationSplited
  test  : /home/ptn/Storage/Research/FFESNet/data/CVC-ClinicDB_Splited/testSplited

model:
  model_name      : 'LA_FFESNet_B0_CVC-ClinicDB'
  model_backbone  : 'B0'

hyparameters:
  init_trainsize  : 352
  batch_size      : 64
  repeats         : 1
  n_epochs        : 200
  learning_rate   : 1e-4
  drop_rate       : 0.2